/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.io.IOException;
import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, IOException {
        // TestCases tests = new TestCases(); // Initialize your test class
        // Search_Amazon search = new Search_Amazon();
        // Hyper_Links links = new Hyper_Links();
        // Linkedin_Post post = new Linkedin_Post();
        // Linkedin_Profile profile = new Linkedin_Profile();
        // Imdb_Ratings imdb = new Imdb_Ratings();
        // Windo_Handling window = new Windo_Handling();
        Iframe_Text ifrmae = new Iframe_Text();

        // Book_My_Show bookShow = new Book_My_Show();
        // TODO: call your test case functions one after other here

        // tests.testCase01();
        // search.searchAmazon();
        // links.hyperLinks();
        // bookShow.bookMyShow();
        // post.linkedinPost();
        // imdb.imdbRatings();
        // window.windowHandling();
        ifrmae.iframeText();

        // profile.linkedInProfile();
        // END Tests
        // search.endTest();
        // links.endTest();
        // bookShow.endTest();
        // tests.endTest(); // End your test by clearning connections and closing
        // browser
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
